### ISSUE TITLE
Support parse/render for custom content types

### ISSUE THREAD

**Issue by chb0github** [jarrodek/advanced-rest-client#10]
Very simple situation:

Accept: application/vnd.api+json

Results back are JSON but are not rendered by the tool in a useful way because, I assume, it is looking at the accept type to find a renderer. If you can open this up so I can at least configure it to use an existing render that would be great.

na przykład:

accept-type                    |  render
----------------------------------------------------
application/vnd.api+json | application/json
application/collection+json | application/json

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report.
This is old repository of the ARC and should not be used. The issue tracker is inactive here and issue reports won't be fixed. Please, go to https://github.com/jarrodek/ChromeRestClient/issues and report the issue there.
