### ISSUE TITLE
Chrome multiple user issue

### ISSUE THREAD

**Issue by bobvanluijt** [jarrodek/advanced-rest-client#5]
Great extension!

I'm using Chrome with 2 users. For one user the ext is working, for another it isn't.

**Comment by jarrodek** [comment]
Hi,

Can you see any error in the console? I'm not sure what is happening.

**Comment by bobvanluijt** [comment]
Hi @jarrodek no error in console, JSON simply doesn't parse

**Comment by jarrodek** [comment]
Can you provide more information? What resource you want to parse? I'm not sure how to reproduce the problem.

**Comment by bobvanluijt** [comment]
O... Did you by any change did an update recently? It's seems to be fixed sorry for not closing.

Thanks :+1:
